### PR TITLE
partially_available? returns false for full availabilities

### LINKED ISSUE #239: When entering an availability, exact same time shows as partially available.
An event has a start time and an end time. If you enter an availability with those exact times, you are listed as `partially available`, not `available`. 
We do not need seconds in these times. A later issue will try to normalize all times to quarter hours.
As you can see from the screen shot, the event is from 7 until 9. Abigal is available during those times, but is only shown as partially available.
The ideal PR would include a test that would expose the bug.

screen shot 2016-10-23 at 6 29 03 pm

### PR DESCRIPTION
**Pull request by EvanTedesco**
this closes #239 and #240

### CODE REVIEW

**Comment by kgf** [comment]
Thanks for your help !
This does address #239, as it now shows available, but the same record still shows twice. See the two Jane Does below.
Would you like me to merge this for 239, or wait for another commit ?

screen shot 2016-10-23 at 9 30 53 pm

**Comment by EvanTedesco** [comment]
This should fix the uniqueness issue.  Would you mind giving me the hacktoberfest flair as well on the PR?  Sorry I don't think I can add labels.

**Comment by kgf** [comment]
Thanks for your help! I think there may be a re factoring in this area, but this gets the correct results. Thanks!

**Comment by kgf** [comment]
Fixes #240

**Pull request merged**
