### PR TITLE
Update _form.html.erb

### PR DESCRIPTION
**Pull request by farrahD**
Added nickname attribute

### CODE REVIEW

**Comment by kgf** [comment]
@farrahD Thanks for contributing to the project. Sadly, this did not pass the test suite. Did you try running the tests locally with `bundle exec rspec` ? 
( If it's the first time you've run them , you may need to run `bundle exec rake db:test:prepare` first )
Let us know if you need any help. 
Thanks again,
Kevin

**Comment by farrahD** [comment]
I ran the tests locally and ran bundle exec rake db:test:prepare first before running bundle exec rspec
What should I do next?

P.S. Thank you for being patient with me through all this. I know the issue I worked on was an easy one but I'm learning as I go. I'm not super familiar with Ruby and databases but have found them quite interesting after working on this.

**Comment by kgf** [comment]
No problem, we like helping folks that are learning. We've all learning !
When you ran the tests locally, they passed ? That surprises me. 
You added the nickname to the form, but you did not add it to the controller, here =>
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/controllers/people_controller.rb#L137
Also, did you try it locally in your browser ? You can start a local server by running `bundle exec rails server` which can be shortened slightly to `bundle exec rails s`. I added an alias on my Mac to allow `bers` from the terminal.

**Comment by farrahD** [comment]
Last night I did add nickname to the controller, not on the line you highlighted but on line 141. Was I supposed to push the branch locally? (Also I ran it in my browser prior to making the changes. How would I 'refresh' it to show the changes I made?)
I'm attaching a screenshot of the changes I made to the controller file and 2 screenshots of the tests I ran last night. At the end of the test it did say:
Finished in 31 minutes 6 seconds (files took 23.67 seconds to load)
669 examples, 0 failures, 10 pending

Randomized with seed 60243
screen shot 2018-03-21 at 12 13 11 pm
screen shot 2018-03-21 at 12 12 23 pm
screen shot 2018-03-21 at 12 08 03 pm

**Comment by kgf** [comment]
Ah, now we're getting somewhere ! If you take a look at the pull request, the controller change is not in there, only the change to the view. That would result in the Travis failures, so that makes sense why tests passed locally and not in Travis. Could you please add that file to the PR ?

**Comment by kgf** [comment]
Thanks @farrahD for your help !
Fixes #664

**Comment by farrahD** [comment]
Your welcome! And thank you for helping to guide me through this! I think this is a great project.

**Comment by kgf** [comment]
If you've enjoyed working on the project, I hope you'll consider picking up another issue. If you have an area of interest, I can probably steer you to an issue in that area.
I can also send you an invite to our slack team.
Thanks,
Kevin

**Comment by farrahD** [comment]
I am considering picking up another issue. I want to get more experience on Github and now that I have this project already setup I hope it will be a little easier for me. My current focus has been on the Front-End, but am open to learning new technologies in general. 
And, I would appreciate an invite to your slack team. I've never used slack before and tried to check it out before realizing it was invite only.

**Comment by kgf** [comment]
Your profile does not have an email to invite. You can send it to me as kfallon@readyresponder.com or post it here...

**Comment by farrahD** [comment]
It's fderderian@yahoo.com
Thanks

**Pull request merged**
