### PR TITLE
Containerized & ran bundle update

### PR DESCRIPTION
**Pull request by masukomi**
More better than the last containerization PR.

I have added a Running in Docker section to the README.md.

NOTE: Not sure if this is going to work with travis. May have to tweak something there.

### CODE REVIEW

**Comment by masukomi** [comment]
Travis says: 

```
apt-get install failed

The command "sudo -E apt-get -yq --no-install-suggests --no-install-recommends $(travis_apt_get_options) install google-chrome-stable" failed and exited with 100 during .
```

not sure where that's coming from...

**Comment by kgf** [comment]
Restarted build to see if it was transient

**Comment by kgf** [comment]
I wonder if it's related to this...
https://stackoverflow.com/questions/55351622/unable-to-install-google-chrome-on-docker

**Comment by kgf** [comment]
That threw a bundler error, so that might be progress!

**Pull request closed without merging**
