### PR TITLE
Added date to Notification#index listing 

### PR DESCRIPTION
**Pull request by vsrnth**
Added date column. This PR is for #717

### CODE REVIEW

**Comment by kgf** [comment]
This will show the created_at on the page, but it is hard to read. Could you please format the time like this ?
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/views/availabilities/_availabilities_table.html.erb#L26
Thanks for your help.
Kevin

**Comment by vsrnth** [comment]
Sure :+1:

**Comment by vsrnth** [comment]
Should I open a new PR since one of the commits is a merge commit?

I do not want to pollute the commit history.

**Comment by kgf** [comment]
That would be fine, thanks.

**Pull request closed without merging**
