### PR TITLE
chore(README): rename LIMS to ReadyResponder :)

### PR DESCRIPTION
**Pull request by aniketmaithani**

### CODE REVIEW

**Comment by aniketmaithani** [comment]
@kgf please review me I think this addresses #172

**Comment by kgf** [comment]
Good morning, 
I appreciate your interest and contribution, but sadly this PR does not actually address issue #172 , which is about changing CONTRIBUTIONS. It does partially address #160, but that has already been assigned to @VanAuken , who is working on a larger update to the entire README.

Would you please modify this to traget the correct file ?
Thanks
Kevin

**Comment by aniketmaithani** [comment]
Hahaha.. I like the `Don't Merge`  Label :P ..  Let me take a look though

**Comment by kgf** [comment]
This pr did not address the issue. I hope  @aniketmaithani  will choose a different issue to tackle.

 Thanks for your interest.
Kevin

**Pull request closed without merging**
