### PR TITLE
43 ruby rmagick versions

### PR DESCRIPTION
**Pull request by DJG86g**
changes made to lock rmagick version as well as downgrading to ruby version from 2.2.2 to 2.1.2 .

### CODE REVIEW

**Comment by kgf** [comment]
Sorry, cannot cleanly merge.
Thanks for your efforts, please resolve this, then I will merge.
You will need to pull development branch into your topic branch.

**Comment by houhoulis** [comment]
@DJG86g This PR still has unrelated changes from other branches included.  Also, you can see in the GitHub UI (this page) that the PR actually can't be merged even if @kgf wanted to: "This branch has conflicts that must be resolved...
Use the command line to resolve conflicts before continuing."

I would be happy to help you rebase or cherry-pick your commits to remove the merge conflicts, and to shape your PR so it only includes the `.ruby-version` file, and the `Gemfile` & `Gemfile.lock` changes to `rmagick`.  However, I am going to look into resolving the dependency issues in a way that allows people to upgrade to Ruby 2.2.  I'll update this ticket with the results.

**Comment by kgf** [comment]
@houhoulis Did you have time to work with @DJG86g on this PR ? It looks like it would merge cleanly now.

**Comment by houhoulis** [comment]
I will reach out to @DJG86g .

**Comment by houhoulis** [comment]
I am still excited about this PR to upgrade our rmagick to v2.15.4.  I've seen segfaults on another project with 2.15.0.

**Comment by houhoulis** [comment]
We do want to upgrade the rmagick gem.  @DJG86g thanks for raising awareness and trying to fix the problem some people have had installing v2.15.0.

The LIMS ruby version has moved on from 2.1.2 to 2.1.8 (and 2.3.0 on Travis CI :two_hearts: ), so I am proposing that we upgrade rmagick in a separate PR ( #102 ) and avoid having to rework AND rebase this PR.  Hope to see you on another PR @DJG86g !

**Comment by houhoulis** [comment]
Superceded by #102 .

**Pull request closed without merging**
