### PR TITLE
Setup coverage

### PR DESCRIPTION
**Pull request by ale7714**
* Also add Code Climate coverage reporting

### CODE REVIEW

**Comment by ale7714** [comment]
@kgf i noticed the repo is already on  Code Climate. if you upload coverage you can use the extension to see the coverage overlay on PRs :)

**Comment by kgf** [comment]
You obviously are knowledgeable in this area. Do you know why code climate doesn't appear as app check the way Travis and codacy do?

Codacy also has the option of tracking test coverage. I did it as a manual step once.

**Comment by ale7714** [comment]
@kgf i see on our admin side that the Pull Request integration is not setup for your repo on Code Climate. You can read this doc https://docs.codeclimate.com/v1.0/docs/workflow to activate it. This status is related to code issues (analysis). 

You will need to merge this PR into development and then following PRs will start receiving [coverage related statuses](https://codeclimate.com/changelog/59baa212ced24c026c0017b8).

**Comment by kgf** [comment]
Interesting. I just noticed that you work for CC. Thanks for your help.

**Comment by kgf** [comment]
@ale7714 I was unable to follow the directions provided. If you're still willing to help on this, I would appreciate it. I went to the settings page for RR, and tried to `Add a service` under integrations. I reached this message
> You're trying to set up a service hook for a repository that lives in the Open Source section of your Dashboard. Unfortunately we don't yet support service hooks for these repositories.

I am a member of the ReadyResponder organization. I don't see any `integrations` tab.
I notice that there *are* webhooks for code climate and codacy. The code climate one goes to
`https://codeclimate.com/webhooks`

**Comment by kgf** [comment]
That said, I think your PR worked, as I now see test coverage in CodeClimate.
😁

**Comment by ale7714** [comment]
@kgf yes, let me check more on this and i'll get back to you.

**Comment by ale7714** [comment]
@kgf 👋 i pointed you to the wrong docs, sorry. You should able to activate the service on your Repo page > Settings on codeclimate.com. You can read in more detail the steps here https://docs.codeclimate.com/v1.0/docs/github#section-pull-requests.

**Comment by kgf** [comment]
Sadly, I do not see the UI described in those docs. I see this.
screen shot 2017-10-11 at 4 09 35 pm
Also, on Code Climate, I do not see ReadyResponder under organizations. Organizations shows RR under `Open Source`

Thanks for your continued help. I would like this integration to work...

**Comment by kgf** [comment]
Sorry, left out a bit. From the CC side, I do not see any tabs beyond `Trends`
screen shot 2017-10-11 at 4 13 41 pm

**Comment by efueger** [comment]
Hi @kgf! Emily here from Code Climate. I have a good idea what's happening 🤔 . 

----
Your probably running into [GitHub's third-party application restrictions](https://help.github.com/articles/about-oauth-app-access-restrictions/) feature. Essentially, if the **ReadyResponder** organization in GitHub has third-party application restrictions enabled, you'll need to allow the Code Climate app to access your repo.

1. Here's a [help doc](https://docs.codeclimate.com/v1.0/docs/approve-code-climate-as-a-third-party-application-in-github) that walks you through that quick third-party approval process.

2. If you don't see the Settings link after you've done those 2 steps, you may need to re-sync your Code Climate user with your GitHub user.

You can do that by clicking on `Add a repository` and then click the Sync now button at the top right of the page:

image

----

Let me know if that gets your Settings link showing! You're almost there. I can feel it👌

**Comment by kgf** [comment]
@efueger Thanks for your help. 
Well, if you're still willing to try, me too. That help doc did not help, unfortunately. It wasn't quite up to date with the current UI, but I did find what I think you're looking for.....
screen shot 2017-10-11 at 5 15 39 pm
After verifying the oauth here, I did re sync.
I am struggling conceptually. Should Ready Responder organization be allowing the authorization, rather than me ?

**Comment by efueger** [comment]
Hi @kgf - Oh man, sorry for this rabbit hole. I think you're correct! 
- Can you try allowing that from ReadyResponder's org Settings page?
- I think that should be here: https://github.com/organizations/ReadyResponder/settings/oauth_application_policy

**Comment by kgf** [comment]
@efueger  No problem, hopefully we'll get there. 
The link above brings me to this page. There is no option to add a new policy from this page.
screen shot 2017-10-12 at 1 24 56 pm

**Comment by efueger** [comment]
@kgf - I think a quick screensharing would be the best way to tackle this.
- Are you available today/sometime this week? (we're on NYC time, ET)
- give me a couple of times and I'll fit you into the schedule 👍

**Comment by kgf** [comment]
How would you attempt the screenshare ? There are limits on what software I could use.

**Comment by efueger** [comment]
HI @kgf - I just sent you an email with a couple of other things to try... And sorry for the delay here! My GitHub notifications don't get answered quite as quickly as those that go through the normal support channel. 

If those steps don't do the trick, we can hop on a call and go screen-by-screen. With or without the actual screenshare 👌

**Comment by kgf** [comment]
@efueger Sadly, I did not receive that email. Could you please send it to kfalllon@readyresponder.org
Thanks for your help.

**Comment by efueger** [comment]
Yep! Just forwarded to you @kgf . 🤞

**Pull request merged**
