### PR TITLE
[WIP] Jheaton/i487/an item should know its inspection questions

### PR DESCRIPTION
**Pull request by saltmade**
This is a 🚧WIP commit for introducing inspection questions through tagging.

### CODE REVIEW

**Comment by saltmade** [comment]
@kgf Still working on this one, but I've got some more time today and tomorrow so I'll see if I can't get into the real questions, which look like:
1. How does the UI handle associating questions and tags?
2. How do we roll up those questions based on tags?

I started with this many to many, polymorphic tag relationship but I'm not convinced I won't have to go back and refactor it depending on how gnarly the queries get. That said I realized the best way to figure that out was by doing so 🤷‍♂️

**Comment by kgf** [comment]
Thanks !
I was asking some associates, they suggested `acts as taggable`. Don't know if you took a look at something like that...

**Comment by kgf** [comment]
This is regarding issue #487.
@jefheaton Are you still looking at this ?

**Comment by saltmade** [comment]
@kgf I am not unfortunately

**Pull request closed without merging**
