### PR TITLE
fix Nokogiri: Gemfile & Gemfile.lock to reduce vulnerabilities

### PR DESCRIPTION
**Pull request by houhoulis**
This pull request is from/with the Snyk service.  See https://github.com/houhoulis/readyresponder/pull/4 for the original PR, created with/by the [Snyk bot](https://github.com/snyk-bot).

Original message:

-----------

The PR fixes one or more vulnerable gems in the dependencies of this project. See the [Snyk test report](https://snyk.io/test/github/houhoulis/readyresponder) for this project for details.

The PR includes:

- Changes to `Gemfile` and `Gemfile.lock` to upgrade the vulnerable dependencies to a fixed version.

##### With an upgrade:
- [SNYK-RUBY-NOKOGIRI-22014](https://snyk.io/vuln/SNYK-RUBY-NOKOGIRI-22014)

Check the changes in this PR to ensure they won't cause issues with your project.

Stay secure,
The Snyk team

```
<!--
snyk:metadata:{"type":"fix","packageManager":"rubygems",
"vulns":["SNYK-RUBY-NOKOGIRI-22014"],"ignore":[],
"upgrade":["SNYK-RUBY-NOKOGIRI-22014"],"isBreakingChange":false,
"changeToGemfile":true,"env":"prod"}
-->
```

### CODE REVIEW

**Comment by houhoulis** [comment]
Question is, do we want all of the `Gemfile` changes, or would we rather do this manually with 1) fewer changes and/or 2) fewer added version specifications.  The added version locks are kind of crufty.

**Comment by kgf** [comment]
The Synk service is interesting.

I updated to head of development. I'll check to see if this cleared the Travis error. I know they were having issues earlier.

**Comment by houhoulis** [comment]
There were over 100 errors in the Travis run, mostly in `spec/support/authentication_helper.rb`, so the problem may be with this upgrade PR.

**Comment by houhoulis** [comment]
yep - for one thing, this PR upgrades jquery-ui-rails from v5 to v6, and to do that, we apparently have to change how we [name our asset files](https://github.com/jquery-ui-rails/jquery-ui-rails#warning)

:sad_trombone:

**Pull request closed without merging**
