### PR TITLE
add created_at, updated_at and last_editor in people show page

### PR DESCRIPTION
**Pull request by sa77**
closing issue #711

### CODE REVIEW

**Comment by kgf** [comment]
Thanks @sa77  !

**Comment by kgf** [comment]
@sa77 I would like to have those shown on all #show pages, if that's of interest. I can create issues, perhaps tomorrow.

**Comment by sa77** [comment]
@kgf yes sure .. i can do that

**Comment by sa77** [comment]
@kgf did you add any other issues related to this ?

**Pull request merged**
