### PR TITLE
Updated favicon

### PR DESCRIPTION
**Pull request by BhaveshSGupta**
#216

### CODE REVIEW

**Comment by kgf** [comment]
When I look at the attached file, it seems to be the same graphic. @BhaveshSGupta, did you commit the wrong file ?

**Comment by BhaveshSGupta** [comment]
I guess I may have, let update it, sorry for inconvenience, btw do have any logo, from which i can make a favicon or should i use the paint one which i have made.

**Comment by kgf** [comment]
Unless you have an interest in graphic design, this may not be a great issue to take on. Perhaps another could tempt you ? If you do still have an interest, I will not be able to discuss this much before Tuesday, but I was thinking of something around the two **RR**s of Ready Responder.
Thanks for your interest !
Kevin

**Comment by BhaveshSGupta** [comment]
I have updated PR please review it now, and it would be great if you could add hacktoberfest label to it thanx!

**Pull request merged**
