### PR TITLE
select only the availabilities whose status is available

### PR DESCRIPTION
**Pull request by aadeshere1**
closes issue #710

### CODE REVIEW

**Comment by aadeshere1** [comment]
@kgf seems this test is failng from the `development` branch.

**Comment by kgf** [comment]
Thanks for your help!
The test suite is correct, because you aren't showing unavailable folks. If you change your select to this scope, I think all will be well.
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/models/availability.rb#L17

**Comment by aadeshere1** [comment]
@kgf I didn't understand the part about changing select to the scope you referred to. Instead i changed the `available` to `cancelled`

**Comment by kgf** [comment]
Thanks for your help.
Scopes are basically a shortcut for what you did in defining a new method. If you change the line in the controller to `event.responses.active`, that will use the scope I referenced earlier. You won't need the change to the model. 
The scope also handles the case of hiding availabilities if people becoming inactive. Scopes typically have better performance.

**Comment by kgf** [comment]
Here is the guide
https://guides.rubyonrails.org/active_record_querying.html#scopes

**Comment by aadeshere1** [comment]
Thanks @kgf. Updated

**Comment by kgf** [comment]
Thanks @aadeshere1 
Since you're in this part of the code, would you be willing to add some tests to ensure cancelled doesn't appear again?

**Comment by aadeshere1** [comment]
@kgf Sure. I'll add the tests too.

**Pull request merged**
