### PR TITLE
Add Vagrant configuration

### PR DESCRIPTION
**Pull request by cesc1989**
This PR implements #108 

I took the job to organize a bit README file so that it looks better on web and added info about how to configure this project with Vagrant

### CODE REVIEW

**Comment by kgf** [comment]
It will take me a little bit to go through that. I'm more familiar with Chef.
It seems you've added a roles directory, which stores the config for Ansible ? If that's true, could you add a README.md with a few lines to that effect ? You could even link to that from the main readme ?

Thanks for your help !

**Comment by cesc1989** [comment]
You bet

**Comment by kgf** [comment]
You know, perhaps you should move most of the Vagrant stuff there and link to it from the readme. Then people who are not interested in Vagrant only have to skip a single line, like `Follow this guide if you would like to set up Ready Responder using Vagrant`
What do you think of that idea, @cesc1989  ?

**Comment by cesc1989** [comment]
LOL. I just ~uploaded~pushed a commit.

I was thinking about first when I was updating the README. Now you said it, makes more sense to me.

Count on it.

**Comment by kgf** [comment]
Great, thanks.
I notice the play book calls for node.js... Where is that used ? (Pretty sure not in RR itself !)

**Comment by cesc1989** [comment]
> Where is that used ?

Ruby on Rails needs a JavaScript runtime environment. One of the available and/or default is the ruby racer but it's way easier when NodeJS is configured in the machine. That's why.

See https://stackoverflow.com/q/7092107/1407371

**Comment by kgf** [comment]
@cesc1989 , thanks for this PR, it's very helpful.

Kevin

**Pull request merged**
