### PR TITLE
Add "Getting Started" section to README.

### PR DESCRIPTION
**Pull request by houhoulis**
Also, genericize `config/database.example.yml`.

### CODE REVIEW

**Comment by houhoulis** [comment]
This would resolve issue #34 by mentioning the phantomjs requirement in the README.

**Comment by kgf** [comment]
Not sure how you could do these two PRs without getting a merge conflict.
Unable to merge

**Comment by kgf** [comment]
BTW, I really like and apprectiate these two PRs.

**Comment by houhoulis** [comment]
---

Kind words @kgf .
Conflicts are impermanent.
The green button waits. :green_heart: 

---

**Comment by kgf** [comment]
This closes #70

**Pull request merged**
