### PR TITLE
adds description to item_type, resolves #345

### LINKED ISSUE #345: Item Type needs description field
Item Type needs description field

### PR DESCRIPTION
**Pull request by abrophy**

### CODE REVIEW

**Comment by kgf** [comment]
Awesome, thanks for your help !

**Comment by kgf** [comment]
@abrophy 
I reverted this, as I merged it too quickly, and there was no migration to change the schema. This would end up being a breaking change for folks. 
Could you please add it and re-submit the PR. 
Thanks !
Kevin

**Comment by abrophy** [comment]
I didn't change the schema as there is already a string field in the item_types table for "description", if that's what you mean. If not what other changes need to be made to the schema?

**Comment by kgf** [comment]
It was my mistake, there was an earlier migration to add the column to the table. I reverted the reversion.

**Pull request merged**
