### PR TITLE
Change inspections to inspectors in association

### PR DESCRIPTION
**Pull request by ChanChar**
Resolves https://github.com/ReadyResponder/ReadyResponder/issues/94

### CODE REVIEW

**Comment by david135** [comment]
Hi @ChanChar, Thanks for your PR.  Could you please re-apply your changes to the most recent `development` branch?  Some of the conflicts preventing your PR from merging look like they might be the result of your changes being based on an old branch.  If you look on your personal branch, you'll see `This branch is 8 commits ahead, 233 commits behind ReadyResponder:development`.  This is a pretty good sign that your branch came off of an out-of-date branch, not `development`.  Ideally, your PR should have changes in only a small number of files, so that we can see what it does in comparison to the `development` branch.  You'll also want to be sure that GitHub tells you that your PR can merge without conflicts.  Let us know if you'd like help figuring out how to do this.

**Comment by ChanChar** [comment]
@david135 yup just noticed that. merged in the updated development branch.

**Comment by david135** [comment]
Thanks for the quick change! I'll let others take a look, now, but some time before the final merge, I'd love to find a way to not include those commits from 2014-2015 in this PR.  That can make following the history of changes confusing.

About your current changes, I wonder if something has gotten reversed in the model:
An `Inspection` is performed by a `Person` on an `Item`.  That person is the `Inspection`'s  inspector.  @kgf, would you please take a look?

**Comment by kgf** [comment]
@houhoulis may well have a different opinion, but given that this is half a dozen lines, might be better to close this and make those changes on a fresh pull from development.

**Comment by kgf** [comment]
Good catch @david135 , that does seem to be reversed.

**Comment by ChanChar** [comment]
Just saw this now. Closing this and will update on a new PR. Thanks guys :]

**Pull request closed without merging**
