### PR TITLE
Add new skill button to skill page

### PR DESCRIPTION
**Pull request by maisieccino**
Addresses issue #237. Adds a "add skill" button to the skill view page.

Let me know if this button should be added to the skill overview page (index) as well.

### CODE REVIEW

**Comment by kgf** [comment]
Sorry, I am learning to write better issues.
I would like this to _only_ be on the index page.

Thanks for your help.
Kevin

**Comment by maisieccino** [comment]
Okay, will update this :smile:

**Comment by maisieccino** [comment]
2016-10-28_112649_scrot

@kgf How's this?

**Comment by kgf** [comment]
That's perfect, thanks for your help.

**Pull request merged**
