### PR TITLE
712 - Don't require rank. [edited: was "Require rank only for active person"]

### PR DESCRIPTION
**Pull request by yasirazgar**
Fixes, https://github.com/ReadyResponder/ReadyResponder/issues/712

When creating or editing a person, rank/title should be required only for person with active status.

### CODE REVIEW

**Comment by houhoulis** [comment]
Hi, @yasirazgar !  Thanks for helping!  Sorry for the delay reviewing your PR.

Could you add a migration to implement the database change?

I also have a question for @VanAuken : #712 requests that "Rank" not be required for statuses "Prospect" or "Applicant".  This PR makes a slightly different change: it _only_ requires "Rank" if the status is "Active".  Should "Rank" be required for the other statuses `'Leave of Absence'`, `'Inactive'`, and `'Declined'`?

**Comment by houhoulis** [comment]
@yasirazgar , it looks as though we can remove the requirement & validation on "Rank" (title) altogether, rather than requiring it conditionally based on Status.  See https://github.com/ReadyResponder/ReadyResponder/issues/712#issuecomment-433659326

**Comment by yasirazgar** [comment]
@houhoulis, removed validation for person#title altogether.

**Review by houhoulis — APPROVED** [review]
thanks!  👍

**Pull request merged**
