### PR TITLE
Resolves issue #378

### PR DESCRIPTION
**Pull request by ghost**
There was a bug in the logic for computing partial availability vs. total availability.

### CODE REVIEW

**Comment by kgf** [comment]
Thanks for your help, I look forward to taking a look at this.

**Comment by kgf** [comment]
I can see where this change could fix it, and I will pull it down locally to test. 
What would make this PR better would be a test that failed before your change, and now passes due to your change. Then this bug can't sneak back in...
Thanks

**Comment by ghost** [comment]
I will do that.

-
Daniel Strimpel
dastrimpel@gmail.com <mailto:dastrimpel@gmail.com>
Blog: https://medium.com/@dastrimpel
Github: https://github.com/danielstrimpel

**Comment by ghost** [comment]
Test added

**Comment by kgf** [comment]
Thanks for your help !

**Pull request merged**
