### PR TITLE
Division fields

### PR DESCRIPTION
**Pull request by pcofilada**
Added new division1 and division2 fields on Department model

### CODE REVIEW

**Comment by pcofilada** [comment]
@kgf Can you check this one? And let me know if there is any other changes you want to make with this.

**Comment by pcofilada** [comment]
#145

**Comment by kgf** [comment]
I really appreciate your help. Could you add some values to the `seeds.rb` file. A department might have  "Team 1" and "Team 2" as division1 values, and "Squad 1" and "Squad 2" as division 2 values. The strings should be serialized arrays so that they can be used as choices on the simple forms
http://stackoverflow.com/questions/19134235/how-to-add-to-a-serialized-array

**Comment by pcofilada** [comment]
@kgf updated.

**Comment by kgf** [comment]
Thanks. Do you know why there were so many changes to schema.rb ?

**Comment by pcofilada** [comment]
Hmmm. Maybe because I'm using the latest ruby version?

**Pull request merged**
