### PR TITLE
Changed ID to title field in the events#show/availabilities view

### PR DESCRIPTION
**Pull request by ghost**
#454

### CODE REVIEW

**Comment by kgf** [comment]
@danielstrimpel Thanks for your help with this. Sadly, this is only partially complete. Since ID was numeric and title is string, it will no longer sort correctly. Take a look at the person#index to see that there is an additional column to give correct sort order. The column is hidden by datatables.
Hopefully this makes sense,
Kevin

**Comment by ghost** [comment]
Thanks I'll go over it again. I was getting a bit hasty, so not surprised stuff was wrong.

**Comment by kgf** [comment]
It's actually not wrong, just incomplete. 
Here is the line in the other view, showing the hidden column
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/views/people/index.html.erb#L9

**Comment by ghost** [comment]
Hi @kgf ,
I'm new to datatables and I'm trying to figure out how it knows which column to sort by and hide. In people/index, it seems to know it's the <th>'s with a (S), but in availabilities table that doesn't work. I changed the availabilities table classname to "datatables" to match the other one but still not working. Can you point me towards the relevant code/documentation for this?
Thanks.

**Comment by kgf** [comment]
I believe this is the block you're looking for...
https://github.com/ReadyResponder/ReadyResponder/blob/development/app/assets/javascripts/events.js.coffee#L9
Also note that you'll need to rebase, as there appear to be conflicts.
Thanks for your help !

**Comment by ghost** [comment]
Thanks @kgf . I have submitted a pr #481 . I got my dev branch up to date with a pull from development on this repo before I started. Im not so familiar with rebase. Is there a reason you suggested that instead of a standard fetch/merge? What conflicts were you referring to?

**Comment by kgf** [comment]
#481 has all these changes and more. I'm going to close this one, and we'll focus on #481

**Pull request closed without merging**
