### PR TITLE
Remove outdated changelog

### PR DESCRIPTION
**Pull request by greysteil**
It looks like this changelog is now very outdated (the last entry was 2013), so should probably be removed.

I'm also interested in whether the tests pass with this cosmetic change, to see whether the failures on #729, #730 and #731 are genuine.

### CODE REVIEW

**Comment by kgf** [comment]
That's a clever tactic. I agree, this is probably not related !

**Comment by kgf** [comment]
This is no longer needed, we got the test suite going again.

**Comment by greysteil** [comment]
Awesome - sorry, was midnight here and I needed some rest. Thanks for picking up!

**Comment by kgf** [comment]
No problem. And I think I'll update the changelog from my comments in the releases section. The test suite fix was all thanks to @buitranquyet

**Pull request closed without merging**
