### PR TITLE
Expired cert should not grant skill

### PR DESCRIPTION
**Pull request by cesc1989**
This PR is a workaround for #15 

The idea is to only return skills for certifications which haven't expired.

### CODE REVIEW

**Comment by cesc1989** [comment]
@kgf please take a look. I haven't added tests yet for this.

Screenshots of how this works:

1. Bad
bad

2. Good
good

Looking forward to your comments.

**Comment by kgf** [comment]
This looks like a valid approach. Thanks for your help !
Kevin

**Comment by cesc1989** [comment]
Cool thing. Then I'd need to make tests pass again and maybe add more.

**Comment by cesc1989** [comment]
@kgf change it to an instance method so that `person_spec` don't break

Waiting for checks to pass.

**Comment by kgf** [comment]
Thanks. I'm watching Travis !

**Comment by kgf** [comment]
Thanks for your help,  @cesc1989

**Pull request merged**
