### PR TITLE
Added gemfile to groups. Enabled built in caching of travis ci

### PR DESCRIPTION
**Pull request by OrthoDex**
I'll look into speeding up the travis build further, maybe through [knapsack](https://github.com/ArturT/knapsack) or [parallel_tests](https://github.com/grosser/parallel_tests).

### CODE REVIEW

**Comment by kgf** [comment]
I re-ran the tests on Travis, and they failed again, same error:

```
1) Channels visits a display page
     Failure/Error: <h2><m%= @channel.person.fullname %>  <%= @channel.name %></h2>

     ActionView::Template::Error:
       undefined method `fullname' for nil:NilClass
     # ./app/views/channels/show.html.erb:8:in `_app_views_channels_show_html_erb___2007759606707425590_71127740'
     # ./app/controllers/channels_controller.rb:21:in `show'
     # ./spec/support/authorization_view_helper.rb:31:in `block in get_basic_editor_views'
     # ./spec/support/database_cleaner.rb:10:in `block (2 levels) in <top (required)>'
     # ------------------
     # --- Caused by: ---
     # NoMethodError:
     #   undefined method `fullname' for nil:NilClass
     #   ./app/views/channels/show.html.erb:8:in `_app_views_channels_show_html_erb___2007759606707425590_71127740'
```

Do these work for you locally, @OrthoDex ?

**Comment by kgf** [comment]
I'm not seeing a relation to the PR....

**Comment by OrthoDex** [comment]
Hey @kgf, so better_errors was causing the failure, I wasn't really expecting that :thinking:  I assumed it would be capistrano related. I put it back in it's grouping, and the tests are passing locally and on travis. I'll try and see why better_errors would be causing this issue, doesn't make sense to me atm.

**Comment by kgf** [comment]
I saw, good work.
Should I hold on this PR then ?

**Comment by OrthoDex** [comment]
Turns out this is an open [issue](https://github.com/charliesome/better_errors/issues/304) on better_errors 

I tried removing web_console but the tests still don't pass. I guess we'll have to wait for a fix before moving better_errors.

**Comment by OrthoDex** [comment]
Alright, so doing this removes the failure:

> #config/environments/test.rb
> config.action_dispatch.show_exceptions = true

Although I feel doing this just to make the tests pass is unneeded. 

Thoughts @kgf ?

**Comment by kgf** [comment]
Thanks for the link. My reading of that issue is that it caused tests to pass that should have failed. We have the opposite issue, tests that should pass are failing. Also, the comment from 

> ppdeassis commented on Jun 19, 2015
> suggested that adding `binding_of_caller` also corrected it for him ?

**Comment by OrthoDex** [comment]
Hey @kgf , putting binding_of_caller along with better_errors in development still results in failure.
image

**Comment by kgf** [comment]
Drat. So what are the options?

**Comment by OrthoDex** [comment]
Well,
1. We keep better_errors and binding_of_caller as it is. I'll try to see if I can contribute to fixing the issue.
2. We do this: 
`#config/environments/test.rb
config.action_dispatch.show_exceptions = true`

According to the rails page:

> ActionDispatch::ShowExceptions rescues any exception returned by the application and renders nice exception pages if the request is local or if config.consider_all_requests_local is set to true. If config.action_dispatch.show_exceptions is set to false, exceptions will be raised regardless.

This should make better errors not respond to any exceptions in that particular test, since there are already rendered exception pages.

**Comment by kgf** [comment]
Let's go with option 2 for now. Thanks for your help !

**Comment by david135** [comment]
Am I right in thinking that 'better_errors' should not be in 'test', regardless of this problem?  [They](https://github.com/charliesome/better_errors) seem to recommend it for 'development' only.

**Comment by kgf** [comment]
I would agree, there's no one there to see it !

**Comment by OrthoDex** [comment]
Hey @kfg , so I have made the needed changes, looks good to go. :smile:

**Comment by kgf** [comment]
Great, I'll take a look in a few minutes

**Comment by kgf** [comment]
Thanks for all your diligence on this.

Kevin

**Comment by kgf** [comment]
This fixes #97

**Pull request merged**
