### PR TITLE
Phone numbers now need to adhere to the ITU standards

### PR DESCRIPTION
**Pull request by kgf**
In the US, this means "+18005551212" style.

### CODE REVIEW

**Comment by masukomi** [comment]
so, without a validation to provide errors when people _don't_ enter numbers that adhere i feel this is just going to be a frustrating issue for users.

**Comment by masukomi** [comment]
also, not all countries have phone numbers of the same length and so the `2..12` is going to be an issue, and I don't see how you're going to distinguish between `+1` country code  followed by a `2` and the `+12` country code (and similar situations).

**Comment by kgf** [comment]
I'll get it working in the US first. Agreed regarding needing a validation

**Comment by kgf** [comment]
Addresses #336

**Comment by kgf** [comment]
There was weirdness in this PR. It has been replaced by PR #356

**Pull request closed without merging**
