### PR TITLE
Delete return to events button

### PR DESCRIPTION
**Pull request by patel-atis**
I deleted the "return to events" button because the navbar's 'events' button links to the same page.

### CODE REVIEW

**Comment by kgf** [comment]
Thanks for your help.
I think the Travis error was a network glitch.
Would you be willing to remove all of the return to event buttons? I believe there is one on task, and one on requirements, and maybe one on assignments.

**Comment by pcai** [comment]
thank you for your contribution! Unfortunately there is now a failing test in `rspec ./spec/features/events/events_spec.rb:172` that expects the text `"Return to"` to be present. Can you please remove this expectation from the test? That should get the test suite passing green again.

**Review by pcai — CHANGES_REQUESTED** [review]
please see failing test on travis

**Comment by kgf** [comment]
@patel-atis Could you please correct that test so we can merge your PR ?
Thanks !

**Comment by kgf** [comment]
@patel-atis We're soo close. Let me know if you need any help to get this finished. Thanks for your help.

**Comment by kgf** [comment]
Thanks for your help @patel-atis

**Pull request merged**
